### ISSUE TITLE
sync not work :((

### ISSUE THREAD

**Issue by gromov-io** [mfuentesg/SyncSettings#112]
```
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.github.com:443 "GET /gists/584da09d137d39283bb5846f9fdc497d HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/b64ae1b3b92602875f3e18f10f327d63328cdd85/sneppets%252Fconsole-dir.sublime-snippet HTTP/1.1" 200 279
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/631726585e018097273080f49334d6f149f412c6/Package%2520Control.merged-ca-bundle HTTP/1.1" 200 207436
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/c1862c68c82a1e305e6669c72f75295c6aba6818/Package%2520Control.cache%252F01524fae79697630d0454ba3fabd9414.info HTTP/1.1" 200 91
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/69d78ee4540b7063a43907df5c02c305ac53a980/Package%2520Control.cache%252F01524fae79697630d0454ba3fabd9414 HTTP/1.1" 200 3430348
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/9e431459b94a6907cb534403f835832ae142e411/sneppets%252Fconsole-log.sublime-snippet HTTP/1.1" 200 280
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/6c2abd4730462ab1afbf2dd7af32a51c63ac2f2b/Package%2520Control.last-run HTTP/1.1" 200 10
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/f3360d83fd9af9f80bd29568c202d51e49661267/Preferences.sublime-settings HTTP/1.1" 200 655
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gist.githubusercontent.com
DEBUG:requests.packages.urllib3.connectionpool:https://gist.githubusercontent.com:443 "GET /gromov-io/584da09d137d39283bb5846f9fdc497d/raw/9055bf782c251d58f14e745c5d2833fcf6f358c6/Package%2520Control.sublime-settings HTTP/1.1" 200 261
ERROR:Sync Settings.sync_settings.libs.logger:'installed_packages'
Traceback (most recent call last):
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/commands/download.py", line 76, in download
    package_settings[setting].append('Sync Settings')
KeyError: 'installed_packages'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `/home/gromov/.config/sublime-text-3/Packages/User/sneppets/console-dir.sublime-snippet`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `/home/gromov/.config/sublime-text-3/Packages/User/Package Control.merged-ca-bundle`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `/home/gromov/.config/sublime-text-3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414.info`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `/home/gromov/.config/sublime-text-3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `/home/gromov/.config/sublime-text-3/Packages/User/sneppets/console-log.sublime-snippet`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'
WARNING:Sync Settings.sync_settings.libs.logger:can`t edit file `/home/gromov/.config/sublime-text-3/Packages/User/Package Control.last-run`
ERROR:Sync Settings.sync_settings.libs.logger:'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 88, in update_files
    edit_content(name, file['content'])
  File "/home/gromov/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/sync_manager.py", line 28, in edit_content
    file_content = content.encode('utf-8', errors='ignore')
AttributeError: 'bytes' object has no attribute 'encode'

```

**Comment by mfuentesg** [comment]
Can you paste the content of `Package Control.sublime-settings` here?

thanks!

**Comment by gromov-io** [comment]
> Можете ли вы вставить содержимое `Package Control.sublime-settings`здесь?
> 
> Спасибо!

```
{
	"color_scheme": "Packages/Theme - One Dark/One Dark.tmTheme",
	"file_exclude_patterns":
	[
		"*.pyc",
		"*.pyo",
		"*.exe",
		"*.dll",
		"*.obj",
		"*.o",
		"*.a",
		"*.lib",
		"*.so",
		"*.dylib",
		"*.ncb",
		"*.sdf",
		"*.suo",
		"*.pdb",
		"*.idb",
		".DS_Store",
		"*.class",
		"*.psd",
		"*.sublime-workspace"
	],
	"folder_exclude_patterns":
	[
		"node_modules",
		".nuxt",
		".idea",
		"*.log",
		"*.min.css",
		"*.min.js",
		"*.css.map",
		".git",
		".hg",
		".svn"
	],
	"font_face": "Ubuntu Mono",
	"font_options":
	[
	],
	"font_size": 12,
	"ignored_packages":
	[
		"SCSS",
		"Vintage"
	],
	"tab_size": 2,
	"theme": "One Dark.sublime-theme"
}

```

**Comment by mfuentesg** [comment]
Thanks, let me check, to fix this bug!

**Comment by mfuentesg** [comment]
@gromov-io sorry, you have pasted your settings file, i need your `Package Control.sublime-settings`

**Comment by gromov-io** [comment]
> @gromov-io sorry, you have pasted your settings file, i need your `Package Control.sublime-settings`

```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"A File Icon",
		"EditorConfig",
		"Emmet",
		"Jade",
		"Package Control",
		"Pug",
		"Sass",
		"Stylus",
		"Sync Settings",
		"Theme - One Dark",
		"Vue Syntax Highlight"
	]
}

```

**Comment by mfuentesg** [comment]
Can you paste the content of `console-log.sublime-snippet` also

**Comment by gromov-io** [comment]
> Can you paste the content of `console-log.sublime-snippet` also

![image](https://user-images.githubusercontent.com/46241127/52540003-dfd27700-2d95-11e9-88ca-80d27d5efc8a.png)

**Comment by mfuentesg** [comment]
@gromov-io please try again, when the release be published!
