### ISSUE TITLE
Cannot download using valid key and gist_id

### ISSUE THREAD

**Issue by kbreit** [mfuentesg/SyncSettings#122]
```
{
    "access_token": "abc123",
    "gist_id": "d21234"
}
```
This is the entirety of my configuration file. I've even created a new key for gist. However, when I try to download from the existing gist I am getting these logs:

```
WARNING:Sync Settings.sync_settings.libs.logger:{'documentation_url': 'https://developer.github.com/v3/#rate-limiting', 'message': "API rate limit exceeded for 73.75.66.18. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
ERROR:Sync Settings.sync_settings.libs.logger:The credentials are invalid, or the token does not have permissions
Traceback (most recent call last):
  File "/home/kbreit/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/commands/download.py", line 45, in download
    ).get(settings.get('gist_id'))
  File "/home/kbreit/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist.py", line 46, in with_gid_wrapper
    return func(self, *args, **kwargs)
  File "/home/kbreit/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist.py", line 83, in get
    return self.__do_request('get', self.make_uri(gid)).json()
  File "/home/kbreit/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist.py", line 100, in __do_request
    raise AuthenticationError('The credentials are invalid, or the token does not have permissions')
Sync Settings.sync_settings.libs.gist.AuthenticationError: The credentials are invalid, or the token does not have permissions
```

**Comment by kbreit** [comment]
Resolved after restart.

**Comment by mfuentesg** [comment]
Cool hahaha
