### ISSUE TITLE
`getaddrinfo failed` behind the proxy on Win10

### ISSUE THREAD

**Issue by marekkaczkowski** [mfuentesg/SyncSettings#123]
Hey,
I can't download gist with settings. Tried with `http/s_proxy` settings with no result.
Can you please share more info about proxy configuration?

- is it python proxy conf
- can I use http://user:pass@myproxy.com:8080 for `http/s_proxy`

```
ERROR:Sync Settings.sync_settings.libs.logger:Can`t perform this action due to network errors. reason: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /gists/xxxxxxxxxxxxxxxxxx (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000029042E21198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\me\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by mfuentesg** [comment]
hey, can you paste here your `Sync Settings.sublime-settings` file content

**Comment by marekkaczkowski** [comment]
```
{
	"access_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"auto_upgrade": false,
	"gist_id": "25ec94537a089e30931e4eceb3fdd5f7",
	"included_files": [],
        "excluded_files":  []
}
```

**Comment by mfuentesg** [comment]
hey, try to use http(s)_proxy properties, to set the a proxy used by sync settings.

```js
    "access_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "auto_upgrade": false,
    "gist_id": "25ec94537a089e30931e4eceb3fdd5f7",
    "included_files": [],
    "excluded_files":  [],

    // proxy options
    "http_proxy": "",
    "https_proxy": ""
}

**Comment by marekkaczkowski** [comment]
Hey, 
added proxies (yes for https should be http proxy) but no differences. Same error `socket.gaierror: [Errno 11001] getaddrinfo failed`.

```
{
...
  "http_proxy": "http://user:pass@myproxy.net:8080",
  "https_proxy": "http://user:pass@myproxy.net:8080",
}
```

**Comment by marekkaczkowski** [comment]
Windoze.. Got it!

`env | grep proxy` returned no results
but `http_proxy` and `https_proxy` was defined in windows env vars (lolz).

Removed both env vars, added again `http_proxy`, `https_proxy` and voila! Works! :tada:

**Comment by mfuentesg** [comment]
happy to hear that,  keep creating cool stuff.
