### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by krupitskas** [mfuentesg/SyncSettings#144]
Hey! Faced a problem.
Maybe it correlates with the new version of sublime text 4070 alpha

![image](https://user-images.githubusercontent.com/5683877/78499493-ad35cb80-7759-11ea-8b4e-a6d301f32009.png)

```
WARNING:Sync Settings.sync_settings.libs.logger:{'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/gists/#delete-a-gist'}
ERROR:Sync Settings.sync_settings.libs.logger:No JSON object could be decoded
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\krupi\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/download.py", line 53, in download
    package_settings = json.loads('{}' if file_content == '' else file_content)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
ERROR:Sync Settings.sync_settings.libs.logger:No JSON object could be decoded
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\krupi\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/download.py", line 53, in download
    package_settings = json.loads('{}' if file_content == '' else file_content)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

My gist 
https://gist.github.com/krupitskas/b272fea836faffa356c8f0cce9a121b3

**Comment by TheSecEng** [comment]
#145 resolves this.
