### ISSUE TITLE
'latin-1' codec can't encode character '\u016f' in position 3227: ordinal not in range(256)

### ISSUE THREAD

**Issue by StephanWells** [mfuentesg/SyncSettings#179]
When trying to run the `Sync Settings: Upload` command, a character encoding error is output and the settings do not upload. This used to work for me up until recently.

Desktop details:
 - MacOS Catalina 10.15.5
 - Sublime Text 3.2.2 Build 3211

Traceback from `sync.log`:

```
ERROR:Sync Settings.sync_settings.libs.logger:'latin-1' codec can't encode character '\u016f' in position 3227: ordinal not in range(256)
Traceback (most recent call last):
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/commands/upload.py", line 28, in upload
    data={'files': files}
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist.py", line 46, in with_gid_wrapper
    return func(self, *args, **kwargs)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist.py", line 73, in update
    return self.__do_request('patch', self.make_uri(gid), data=sublime.encode_value(data, True)).json()
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/api.py", line 140, in patch
    return request('patch', url,  data=data, **kwargs)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/adapters.py", line 439, in send
    timeout=timeout
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/stephanwells/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1102, in _send_request
UnicodeEncodeError: 'latin-1' codec can't encode character '\u016f' in position 3227: ordinal not in range(256)
```

**Comment by mfuentesg** [comment]
@StephanWells do you have the latest version of the plugin?

**Comment by mfuentesg** [comment]
you are not using the latest version, because the following portion of code is not in the latest version.

Try to use `Package Control: Upgrade Package` command, in order to use the latest version.
```
    return self.__do_request('patch', self.make_uri(gid), data=sublime.encode_value(data, True)).json()
```
