### ISSUE TITLE
SSL cert error when attempting to Create and Upload

### ISSUE THREAD

**Issue by wvpv** [mfuentesg/SyncSettings#198]
**Describe the bug**
I'm attempting to Create and Sync in a new Sublime Text 4 installation, but I'm getting an SSL certificate error as indicated below.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2
 - Sublime Version: v4 build 4121

**Log file content with debug property in true**
```
ERROR:Sync Settings.sync_settings.libs.logger:Can`t perform this action due to network errors. reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\util\ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "./python3.3/ssl.py", line 246, in wrap_socket
  File "./python3.3/ssl.py", line 350, in __init__
  File "./python3.3/ssl.py", line 346, in __init__
  File "./python3.3/ssl.py", line 553, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 439, in send
    timeout=timeout
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Roaming\Sublime Text\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 92, in __do_request
    response = getattr(requests, verb)(url, headers=self.headers, proxies=self.proxies, **kwargs)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\redacted\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\adapters.py", line 513, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Roaming\Sublime Text\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/create_and_upload.py", line 45, in create
    ).create(data)
  File "C:\Users\redacted\AppData\Roaming\Sublime Text\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 36, in auth_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\redacted\AppData\Roaming\Sublime Text\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 66, in create
    return self.__do_request('post', self.make_uri(), data=json.dumps(data)).json()
  File "C:\Users\redacted\AppData\Roaming\Sublime Text\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 94, in __do_request
    raise NetworkError('Can`t perform this action due to network errors. reason: {}'.format(str(e)))
Sync Settings.sync_settings.libs.gist.NetworkError: Can`t perform this action due to network errors. reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)
```

**Comment by wvpv** [comment]
It does appear that there's a proxy in play on my machine.  Is there a way for me to reference a cert locally via Sync Settings config?

**Comment by mfuentesg** [comment]
Hi @wvpv , sorry, but it is not possible to define certs at config file level. You are welcome to contribute to it.
