### ISSUE TITLE
file or directory does not exist

### ISSUE THREAD

**Issue by TheChrisPratt** [mfuentesg/SyncSettings#3]
I followed the installation instructions exactly.

Created the access token on GitHub
Copied the access token value to `User\SyncSettings.sublime-settings`

Nothing happened!

So I tried the *Preferences* -> *Package Settings* -> *Sync Settings* -> *Sync Settings: Create and Upload* (since it seemed like a likely next step).  It prompts me for a *Gist Description* then gives me the error `file or directory does not exist` in the status bar.

What am I missing?
  (*Chris*)

**Comment by mfuentesg** [comment]
Hey Chris, i am working in a logger file to save these errors.

Please send me a screen capture of the error.

**Comment by mhenrixon** [comment]
This is the output from my end

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 441, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 387, in is_enabled
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 314, in file_type
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 145, in load_config
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 167, in bundler_support
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 237, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 437, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'split_view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 441, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 387, in is_enabled
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 314, in file_type
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 145, in load_config
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 167, in bundler_support
  File "run_ruby_test in /Users/mhenrixon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 237, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
```

**Comment by mfuentesg** [comment]
The new version has a error logger
