### ISSUE TITLE
stopped working 

### ISSUE THREAD

**Issue by myasseen** [mfuentesg/SyncSettings#34]
No matter how I tried to create and upload, it shows me a progress and the sublime status bar but nothing uploaded and no logs recorded.

I tried to uninstall and reinstall.

I am sure of the access token and the gist Id it was working before but all of a sudden it stopped working.

it will be appreciated if you can help.

**Comment by mfuentesg** [comment]
Thanks for your feedback!

I will review that.

**Comment by mfuentesg** [comment]
it is rare, because i have not uploaded a new version.

I am try to test some common bugs, but the plugin is working without problems.

**Comment by myasseen** [comment]
so what do you think the problem could be?
is it the os, the windows firewall, the sublime it self, the gist (private / public)??

**Comment by myasseen** [comment]
Traceback (most recent call last):
  File "sync_settings.sync_settings_manager in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 115, in gist_api
  File "sync_settings.libs.gistapi in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 12, in __init__
  File "E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\sublime-github.sublime-package\lib\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\sublime-github.sublime-package\lib\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\sublime-github.sublime-package\lib\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\sublime-github.sublime-package\lib\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\sublime-github.sublime-package\lib\requests\adapters.py", line 331, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sync_settings.commands.create_and_upload in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 28, in create_and_upload_request
  File "sync_settings.sync_settings_manager in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 117, in gist_api
  File "sync_settings.sync_settings_manager in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 77, in show_message_and_log
AttributeError: 'SSLError' object has no attribute 'to_json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "sync_settings.commands.create_and_upload in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 49, in <lambda>
  File "sync_settings.commands.create_and_upload in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 45, in create_and_upload_request
  File "sync_settings.sync_settings_manager in E:\Software\Portable Apps Menu\PortableApps\Sublime Text Build 3065 x64\Data\Installed Packages\Sync Settings.sublime-package", line 77, in show_message_and_log
AttributeError: 'AttributeError' object has no attribute 'to_json'

**Comment by myasseen** [comment]
Sorry for bothering you.

it was some other git plugin that causes this plugin to stop working, I un-installed all git plugins and all is OK now.

**Comment by mfuentesg** [comment]
No problem!
