### ISSUE TITLE
sync_settings_cache links to wrong directory

### ISSUE THREAD

**Issue by kromonos** [mfuentesg/SyncSettings#42]
OS: Windows 10 Pro x64
ST: 3 Build 3114 64Bit
```
Fail to create the file C:\Users\achten\Documents\Portable Apps\Sublime Text Build 3114 x64\Data\Installed Packages\Sync Settings.sublime-package\.sync_settings_cache - [Errno 2] No such file or directory: 'C:\\Users\\achten\\Documents\\Portable Apps\\Sublime Text Build 3114 x64\\Data\\Installed Packages\\Sync Settings.sublime-package\\.sync_settings_cache'
An exception in file C:\Users\achten\Documents\Portable Apps\Sublime Text Build 3114 x64\Data\Installed Packages\Sync Settings.sublime-package\.sync_settings_cache - [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\achten\\Documents\\Portable Apps\\Sublime Text Build 3114 x64\\Data\\Installed Packages\\Sync Settings.sublime-package': 
Error in file C:\Users\achten\Documents\Portable Apps\Sublime Text Build 3114 x64\Data\Installed Packages\Sync Settings.sublime-package\.sync_settings_cache - [Errno 2] No such file or directory: 'C:\\Users\\achten\\Documents\\Portable Apps\\Sublime Text Build 3114 x64\\Data\\Installed Packages\\Sync Settings.sublime-package\\.sync_settings_cache'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "sync_settings.sync_version in C:\Users\achten\Documents\Portable Apps\Sublime Text Build 3114 x64\Data\Installed Packages\Sync Settings.sublime-package", line 21, in check_version
  File "sync_settings.sync_version in C:\Users\achten\Documents\Portable Apps\Sublime Text Build 3114 x64\Data\Installed Packages\Sync Settings.sublime-package", line 45, in has_cache
TypeError: argument of type 'NoneType' is not iterable
```
Maybe you want to change from \Data\Installed Packages\Sync Settings.sublime-package\ to \Data\Packages\Sync Settings\ like other plugins do?

**Comment by mfuentesg** [comment]
Hi, i will try with a portable version. ;)

Thanks

**Comment by kromonos** [comment]
Maybe same problem on installed version:
```
An exception in file C:\Program Files\Sublime Text 3\Data\Installed Packages\Sync Settings.sublime-package\.sync_settings_cache - [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Program Files\\Sublime Text 3\\Data\\Installed Packages\\Sync Settings.sublime-package'
```

**Comment by xdmiodz** [comment]
looks like the issue makes the plugin worthless - I can't download my backup from gist to a fresh sublime installation. even more, the plugin removes itself in the process!

**Comment by xdmiodz** [comment]
Here is what happens when I try to download a backup with SyncSettings

Mac OS X, ST3


```
reloading settings Packages/User/SyncSettings.sublime-settings
An exception in file /Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/.sync_settings_cache - [Errno 17] File exists: '/Users/dmitry/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package': 
```

**Comment by sdouche** [comment]
same thing happens to me:
```
Fail to create the file /home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/.sync_settings_cache - [Errno 20] Not a directory: '/home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/.sync_settings_cache'
An exception in file /home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/.sync_settings_cache - [Errno 17] File exists: '/home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package': 
Error in file /home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/.sync_settings_cache - [Errno 20] Not a directory: '/home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package/.sync_settings_cache'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "sync_settings.sync_version in /home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 21, in check_version
  File "sync_settings.sync_version in /home/sdouche/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 45, in has_cache
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by mfuentesg** [comment]
I know this bug and i am working on it. Thanks for your feedback
