### ISSUE TITLE
Download doesn't work and clears Gist ID

### ISSUE THREAD

**Issue by skegel13** [mfuentesg/SyncSettings#46]
I am having an issue downloading my settings. I am using dev version 3122 on Linux Mint. I had no issues with the same version on Windows 10.

Whenever I click download, the Gist ID is removed from my settings and nothing is downloaded. Here is the output from the console (the sync settings log is blank):

```
Exception in thread Thread-17:
Traceback (most recent call last):
  File "sync_settings.commands.download in /home/sean/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 24, in __download_request
  File "sync_settings.sync_manager in /home/sean/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 139, in update_from_remote_files
  File "sync_settings.sync_manager in /home/sean/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 139, in <listcomp>
  File "sync_settings.libs.utils in /home/sean/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 274, in decode_path
AttributeError: 'module' object has no attribute 'unquote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "sync_settings.commands.download in /home/sean/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 46, in <lambda>
  File "sync_settings.commands.download in /home/sean/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 38, in __download_request
  File "sync_settings.sync_logger in /home/sean/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 24, in log
AttributeError: 'AttributeError' object has no attribute 'to_json'
```

**Comment by jt3k** [comment]
i have same problem.

how to fix it ?

**Comment by mfuentesg** [comment]
hi @jt3k i am working on this bug, soon you will have news

**Comment by JeremyNikolic** [comment]
Hi,
Another case of disapearing gist_id.

At work we have a restricted network which block the connection to certain remote addresses.
If I'm on this restricted network and try download or upload, as the gist can not be reached nothing happens and the gist_id is removed, it would be nice to have a message or at least not clear the gist_id.
At the moment I have to check which netwrok I'm on before trying to upload/download.

in case this can help, here's the trace:

> Trad: "Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée" 
> -> "No connection could be established because target machine actively refused it"

```
Exception in thread Thread-195:
Traceback (most recent call last):
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connection.py", line 204, in connect
    conn = self._new_conn()
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\util\connection.py", line 88, in create_connection
    raise err
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\util\connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\util\retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\packages\six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connection.py", line 204, in connect
    conn = self._new_conn()
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\util\connection.py", line 88, in create_connection
    raise err
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\packages\urllib3\util\connection.py", line 78, in create_connection
    sock.connect(sa)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(10061, 'Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée', None, 10061))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sync_settings.sync_manager in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 166, in gist_api
  File "sync_settings.libs.gist_api in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 21, in __init__
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\DATA\Tools\SUBLIME\Data\Packages\requests\all\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(10061, 'Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée', None, 10061))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sync_settings.commands.upload in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 17, in __upload_request
  File "sync_settings.sync_manager in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 168, in gist_api
  File "sync_settings.sync_logger in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 24, in log
AttributeError: 'ConnectionError' object has no attribute 'to_json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "sync_settings.commands.upload in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 46, in <lambda>
  File "sync_settings.commands.upload in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 38, in __upload_request
  File "sync_settings.sync_logger in C:\DATA\Tools\SUBLIME\Data\Installed Packages\Sync Settings.sublime-package", line 24, in log
AttributeError: 'AttributeError' object has no attribute 'to_json'

```

**Comment by mfuentesg** [comment]
Thanks @JeremyNikolic

**Comment by jt3k** [comment]
fixed ?

**Comment by mfuentesg** [comment]
soon i will release a new version
