### ISSUE TITLE
Fails with Dev Channel, Build 3125

### ISSUE THREAD

**Issue by ferronrsmith** [mfuentesg/SyncSettings#58]
[28/09/2016 - 23:00:02] ERROR: ['Traceback (most recent call last):\n', '  File "sync_settings.commands.download in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 25, in __download_request\n', "KeyError: 'SyncSettings.sublime-settings'\n"]
[28/09/2016 - 23:00:17] ERROR: ['Traceback (most recent call last):\n', '  File "sync_settings.commands.upload in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 20, in __upload_request\n', '  File "sync_settings.sync_manager in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 91, in get_files_content\n', '  File "sync_settings.sync_manager in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 51, in get_filtered_files\n', '  File "sync_settings.libs.utils in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 42, in merge_lists\n', "NameError: global name 'reduce' is not defined\n"]

**Comment by ildarkhasanshin** [comment]
+1
3126

**Comment by mfuentesg** [comment]
Thanks @ferronrsmith

**Comment by ferronrsmith** [comment]
This bug is still present
