### ISSUE TITLE
 Fails with Dev Channel, Build 3125

### ISSUE THREAD

**Issue by ferronrsmith** [mfuentesg/SyncSettings#63]
Same as : #58 

[01/10/2016 - 23:58:34] ERROR: ['Traceback (most recent call last):\n', '  File "sync_settings.commands.upload in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 20, in __upload_request\n', '  File "sync_settings.sync_manager in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 91, in get_files_content\n', '  File "sync_settings.sync_manager in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 51, in get_filtered_files\n', '  File "sync_settings.libs.utils in /home/ferron/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 42, in merge_lists\n', "NameError: global name 'reduce' is not defined\n"]

**Comment by ferronrsmith** [comment]
When I moved reduce outside the try catch. Seems to be failing there


```javascript
try:
  from urllib import parse
  from functools import reduce
except Exception as e:
  import urllib as parse
```

I now get


[02/10/2016 - 00:22:26] ERROR: 'module' object has no attribute 'quote'
[02/10/2016 - 00:22:26] ERROR: 'module' object has no attribute 'quote'
[02/10/2016 - 00:22:26] ERROR: 'module' object has no attribute 'quote'
[02/10/2016 - 00:22:26] ERROR: 'module' object has no attribute 'quote'
[02/10/2016 - 00:22:26] ERROR: 'module' object has no attribute 'quote'
[02/10/2016 - 00:22:26] ERROR: 'module' object has no attribute 'quote'
[02/10/2016 - 00:22:26] ERROR: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by ferronrsmith** [comment]
Submitted : https://github.com/mfuentesg/SyncSettings/pull/64
