### ISSUE TITLE
Syncing not works

### ISSUE THREAD

**Issue by jt3k** [mfuentesg/SyncSettings#67]
i update sync-settings to version 2.4.2 on my laptop (from apple) and on my computer (apple).

i upload settings on computer 
and download settings on laptop

After restart sublimetext_on_laptop in command-pallete (cmd+shift+p)  i not find many menu items. (e.g. sync settings upload)

**FIX IT** plz and Close the issue  **AFTER** fixing. 

thnx.

**Comment by mfuentesg** [comment]
Paste the log file content here

macOS: `cat ~/.sync-settings.log | pbcopy`

**Comment by jt3k** [comment]
my ~/.sync-settings.log from laptop
```
[03/10/2016 - 15:40:03] ERROR: It has generated an error when to update or create the file /Users/jt3k/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings - No JSON object could be decoded
[03/10/2016 - 15:43:52] ERROR: ['Traceback (most recent call last):\n', '  File "sync_settings.sync_version in /Users/jt3k/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package", line 27, in check_version\n', '  File "sync_settings.libs.gist_api in /Users/jt3k/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package", line 148, in get\n', "TypeError: Can't convert 'NoneType' object to str implicitly\n"]
[03/10/2016 - 20:59:34] ERROR: It has generated an error when to update or create the file /Users/jt3k/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings - No JSON object could be decoded
[03/10/2016 - 21:02:05] ERROR: It has generated an error when to update or create the file /Users/jt3k/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings - No JSON object could be decoded
```

**Comment by mfuentesg** [comment]
Please, paste the `Package Control.sublime-settings`file content here

**Comment by jt3k** [comment]
Package Control.sublime-settings
```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Package Control",
		"Sync Settings"
	]
}
```

**Comment by adeonir** [comment]
I got a similar error:

```
[11/10/2016 - 07:33:03] ERROR: It has generated an error when to update or create the file /Users/adeonir/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings - No JSON object could be decoded
[11/10/2016 - 07:39:17] ERROR: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by mfuentesg** [comment]
@adeonir this appears during the download process?

Can you paste the `Package Control.sublime-settings` file content?

```bash
cat ../Packages/User/Package Control.sublime-settings
And from
gist.github.com/<gist_id> (Package Control.sublime-settings

**Comment by mfuentesg** [comment]
@jt3k can you paste the `Package Control.sublime-settings` file content from `gist.github.com/...`

**Comment by jt3k** [comment]
i try "Create and Upload" on computer    (after this  my gist id is refreshed in **SyncSettings.sublime-setings**)

Then i copy **SyncSettings.sublime-setings** to my laptop, and try "Download settings"
after restart nothing happened.

this my secret  gist https://gist.github.com/jt3k/1ec07b25350de2d1098d515e91bb5d5e if it helps

**Package Control.sublime-settings** file
```json
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"AceJump",
		"Babel",
		"Colorcoder",
		"Console Wrap for js",
		"DocBlockr",
		"EditorConfig",
		"ES6-Toolkit",
		"ESLint-Formatter",
		"FindSelected",
		"FuzzyFilePath",
		"Git",
		"GitGutter",
		"Handlebars",
		"Hayaku - tools for writing CSS faster",
		"Jade",
		"JsFormat",
		"LESS",
		"memTask",
		"Package Control",
		"ProjectManager",
		"Pug",
		"Stylus",
		"SublimeLinter",
		"SublimeLinter-contrib-bootlint",
		"SublimeLinter-contrib-eslint",
		"SublimeLinter-contrib-htmlhint",
		"Sync Settings",
		"SyncedSideBar",
		"Terminal",
		"TernJS",
		"TodoReview",
		"TrailingSpaces",
		"UMD snippets",
		"Vanilla lodash Snippets"
	]
}
```

after trying  download settings  in  my  .sync-settings.log adds  this line
```
[11/10/2016 - 14:34:14] ERROR: It has generated an error when to update or create the file /Users/jt3k/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings - No JSON object could be decoded
```

Content of my Package-control.cublime-settings
```json
{
  "bootstrapped": true,
  "in_process_packages": [],
  "installed_packages": [
    "Package Control",
    "Sync Settings"
  ]
}
```

**Comment by mfuentesg** [comment]
thanks @jt3k

**Comment by adeonir** [comment]
@mfuentesg same happend here.
And I forgot to mention before, i'm using build 3126.

**Comment by jt3k** [comment]
me too 3126

**Comment by sdouche** [comment]
I had the same issue. I created a new gist and now it works.

**Comment by jt3k** [comment]
@sdouche 
i try this
not works for me...
what is your operating system?

**Comment by sdouche** [comment]
sorry @jt3k I can't remember what I do to fix the issue. I'm on Linux.

**Comment by mfuentesg** [comment]
@jt3k or @adeonir 
can you share me your conflictive gist? Thanks

**Comment by jt3k** [comment]
yep https://gist.github.com/jt3k/1b6bb463389393d1b28157dfa2faee7e

**Comment by adeonir** [comment]
here: https://gist.github.com/adeonir/16d514294345a908e0c3b5c338bfdc43

**Comment by mfuentesg** [comment]
@jt3k your file has the follow information

it is very weird because the content is empty and the file size is 1327 Kb 
```json
{
    "type": "text/plain",
    "raw_url": ".../Package%2520Control.sublime-settings",
    "language": null,
    "filename": "Package%20Control.sublime-settings",
    "truncated": true,
    "content": "",
    "size": 1327
}

**Comment by jt3k** [comment]
@mfuentesg  I will be on holiday for weaks.  After this i try delete all config-files and reinstall plugins.

**Comment by lestevam** [comment]
I have had the same problems. I set my gist_id and the access_token, but when I run the "Download" command, it shows me the success message (in green) and asks to restart the ST. After the restart my settings are not loaded, so when I see the log file, generated the following error:

[20/10/2016 - 16:47:47] ERROR: It has generated an error when to update or create the file /home/luizestevam/.config/sublime-text-3/Packages/User/Package Control.sublime-settings - No JSON object could be decoded

The local and remote file are correct as tested with JSONLint.

Tks!

**Comment by mfuentesg** [comment]
@lestevam can you share me your gist link?

Thanks

**Comment by lestevam** [comment]
Yes, see: https://gist.github.com/lestevam/42db9ade45a564d4c37d7891b5891c7f

Thanks!

**Comment by mfuentesg** [comment]
@lestevam @jt3k @adeonir I don't know why your files this behavior.

So, the request returned the following response:

```json
"SyncSettings.sublime-settings": {
      "filename": "SyncSettings.sublime-settings",
      "type": "text/plain",
      "language": null,
      "raw_url": "https://gist.githubusercontent.com/lestevam/42db9ade45a564d4c37d7891b5891c7f/raw/8c47d9faeb42178f12ed4f2f17c4cd07516314e8/SyncSettings.sublime-settings",
      "size": 390,
      "truncated": true,
      "content": ""
}
```
**truncated: true** and **raw_url** is the key.
I am will update the plugin to accept this cases getting the file content from the `raw_url`

**Comment by jt3k** [comment]
YEPP! NOW IT WORKS!!! 

THNX @mfuentesg !

**Comment by Nicksxs** [comment]
i have same problem
https://gist.github.com/Nicksxs/c19256dac4968eeeac447541b653ba4b
