### ISSUE TITLE
Can't edit/create/upload settings

### ISSUE THREAD

**Issue by BPagoaga** [mfuentesg/SyncSettings#94]
I had an alert while trying to upload my settings to an existing gist. The message asked to open an issue with the last log :

```
ERROR: ['Traceback (most recent call last):',
 '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 451, in _update_chunk_length  
   self.chunk_left = int(line, 16)',
 "ValueError: invalid literal for int() with base 16: b''",
  'During handling of the above exception, another exception occurred:',

 'Traceback (most recent call last):',
 '  File "/home/wda/.config/sublime-text 3/Packages/requests/all/requests/packages/urllib3/response.py", line 232, in _error_catcher  
   yield',
 '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 502, in read_chunked  
   self._update_chunk_length()',
 '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 455, in _update_chunk_length  
   raise httplib.IncompleteRead(line)',
  'http.client.IncompleteRead: IncompleteRead(0 bytes read)',
  'Du
  ring handling of the above exception, another exception occurred:',
  'Traceback (most recent call last):',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 676, in generate  
   for chunk in self.raw.stream(chunk_size, decode_content=True):',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 353, in stream  
   for line in self.read_chunked(amt, decode_content=decode_content):',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 530, in read_chunked  
   self._original_response.close()',
  '  File "./python3.3/contextlib.py", line 66, in __exit__',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/packages/urllib3/response.py", line 250, in _error_catcher  
   raise ProtocolError(\'Connection broken: %r\' % e, e)',
  "requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))",
  'Du
  ring handling of the above exception, another exception occurred:',
  'Traceback (most recent call last):',
  '  File "sync_settings.commands.upload in /home/wda/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 26, in __upload_request',
  '  File "sync_settings.libs.gist_api in /home/wda/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package", line 82, in edit',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/api.py", line 136, in patch  
   return request(\'patch\', url,  data=data, **kwargs)',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/api.py", line 56, in request  
   return session.request(method=method, url=url, **kwargs)',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 475, in request  
   resp = self.send(prep, **send_kwargs)',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/sessions.py", line 628, in send  
   r.content',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 755, in content  
   self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()',
  '  File "/home/wda/.config/sublime-text-3/Packages/requests/all/requests/models.py", line 679, in generate  
   raise ChunkedEncodingError(e)',
  "requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))"]

```

I can't either create and upload settings, or manually create a gist and upload my settings.

**Comment by BPagoaga** [comment]
Nevermind, I simply did not allow the sync settings token to access gist...
